server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esta línea evita el error 404 cuando refrescas la pantalla en React/Vue
        try_files $uri $uri/ /index.html;
    }
}